apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: culinary-backend:v1
          imagePullPolicy: IfNotPresent  # Báo cho K8s dùng image bạn vừa build trên máy
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "postgres-service"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
